### ISSUE TITLE
Cannot destructure property 'title' of 'projectDetail' as it is undefined.

### ISSUE THREAD

**Issue by aryanjha256** [uzzii-21/astro-portfolio#2]
when labelling feature: false for a project then there is a showing:
Cannot destructure property 'title' of 'projectDetail' as it is undefined.

**Comment by aryanjha256** [comment]
even whenever i try to add more than 6 projects this error occurs, without even using "feature" in info.ts as keeping it default as true

**Comment by JusJira** [comment]
try replacing
`const featureProjects = info.projects.map((project, index) => {
  if (project.isFeatured && index < 6) {
    return project;
  }
});`

with this

`const featureProjects = info.projects.reduce((featureProjects, project, index) => {
  if (project.isFeatured && index < 6) {
    featureProjects.push(project)
  }
  return featureProjects
},[]);`

in pages/index.astro

**Comment by phibkro** [comment]
it also worked for me to just replace 
`const featureProjects = info.projects.map(`
with
`const featureProjects = info.projects.filter(`

**Comment by d5732** [comment]
#4

**Comment by uzzii-21** [comment]
can you create a PR for this ?
